<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Title>GCNTools</Title>
        <Authors>GCNTools contributors</Authors>
        <Description>GCNTools is a simple, platform-agnostic C# .NET library for working with GameCube discs, including reading, extracting, and creating disc images.</Description>
        <PackageProjectUrl>https://worktree.ca/parham/GCNTools</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://worktree.ca/parham/GCNTools</RepositoryUrl>
        <PackageTags>gamecube</PackageTags>
        <PackageReleaseNotes>- Fixed file system table generation</PackageReleaseNotes>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Copyright>Copyright © GCNTools contributors</Copyright>
        <Version>1.0.2</Version>
    </PropertyGroup>
	
	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="/" Visible="false" />
	</ItemGroup>
	
</Project>
